### ISSUE TITLE
idea/suggestion: Html to Feliz translation 

### ISSUE THREAD

**Issue by jkone27** [dbrattli/Feliz.ViewEngine#18]
some translator for HTML would be really nice to have :)

like this one for fable : 
https://mangelmaxime.github.io/html-to-elmish/

maybe a similar version can be adapted for Feliz

**Comment by Zaid-Ajaj** [comment]
It's already there, checkout [Html2Feliz](https://thisfunctionaltom.github.io/Html2Feliz)

**Comment by jkone27** [comment]
Thanks !
