### ISSUE TITLE
Make the library Fable-compatible

### ISSUE THREAD

**Issue by Zaid-Ajaj** [dbrattli/Feliz.ViewEngine#3]
This library is not yet suitable to be consumed from a Fable project because it doesn't yet include the sources of the library into a nuget package. You have to add this section into the .fsproj file 
```xml
 <ItemGroup>
        <Content Include="*.fsproj; *.fs; *.js;" PackagePath="fable\" />
</ItemGroup>
```
Even if it WIP, it might be a good idea to publish a prerelease version or even simply 0.1.0 version to make easy for people to give it a try early on and get feedback

**Comment by dbrattli** [comment]
Thanks, had forgot. Have added now, and [Feliz.ViewEngine](https://www.nuget.org/packages/Feliz.ViewEngine/) is now auto-publishing to NuGet when new tags are pushed using [Github actions](https://github.com/dbrattli/Feliz.ViewEngine/actions)

**Comment by Zaid-Ajaj** [comment]
Great! That makes things much easier :rocket:
